/**
 * PearPass backend API server (port 3001, CORS-enabled).
 *
 * Exposes the private-election DApp as a small REST API for the separate
 * frontend server (port 3000). Reuses the exact provider/wallet wiring from
 * the CLI so the browser never touches secrets: proofs are generated by the
 * local proof-server, ballots are submitted over the devnet, and only public
 * data (question, tally, ballot ids) is served.
 *
 * Endpoints:
 *   GET  /api/status   public ledger + tally + audit check
 *   GET  /api/balance  wallet tNIGHT / DUST (authority account)
 *   POST /api/vote     { choice: "for" | "against" }  (may take 30-60s)
 *   POST /api/close    close the election (authority only)
 */
import { Buffer } from 'buffer';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { WebSocket } from 'ws';

// @ts-expect-error Required for wallet sync
globalThis.WebSocket = WebSocket;

import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { resolveNetwork, getOrCreateWallet, getDeployment, type DeploymentRecord } from './network';
import { createWallet, persistWalletState, unshieldedToken, type WalletContext } from './wallet';
import { compiledContract, CONTRACT_TAG, decodeLedger, zkConfigPath } from './contract';
import { newBallotSecret, ballotIdFromSecret, toHex } from './keys';

const PORT = Number(process.env.API_PORT || 3001);
const ADMIN_PRIVATE_STATE_ID = 'electionAdminPrivateState';

// ─── Network & wallet ──────────────────────────────────────────────────────────

const { network, config: networkConfig } = resolveNetwork();
const WALLET = getOrCreateWallet(network);
const SEED = WALLET.seed;

function requireDeployment(): DeploymentRecord {
  const dep = getDeployment(network);
  if (!dep) {
    console.error(`\n❌ No deploy on file for network ${network}. Run \`npm run setup -- --network ${network}\` first.\n`);
    process.exit(1);
  }
  return dep;
}

const deployment = requireDeployment();

// ─── Providers (mirrors src/cli.ts) ────────────────────────────────────────────

async function createProviders(walletCtx: WalletContext) {
  const privateStatePassword =
    process.env.PRIVATE_STATE_PASSWORD?.trim() || 'Local-Devnet-Development-Placeholder-1';

  const walletProvider = {
    getCoinPublicKey: () => walletCtx.shieldedSecretKeys.coinPublicKey,
    getEncryptionPublicKey: () => walletCtx.shieldedSecretKeys.encryptionPublicKey,
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await walletCtx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: walletCtx.shieldedSecretKeys, dustSecretKey: walletCtx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return walletCtx.wallet.finalizeRecipe(recipe);
    },
    submitTx: (tx: any) => walletCtx.wallet.submitTransaction(tx) as any,
  };

  const zkConfigProvider = new NodeZkConfigProvider(zkConfigPath);
  const accountId = walletCtx.unshieldedKeystore.getBech32Address().toString();

  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: 'private-election-state',
      accountId,
      privateStoragePasswordProvider: () => privateStatePassword,
    }),
    publicDataProvider: indexerPublicDataProvider(networkConfig.indexer, networkConfig.indexerWS),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(networkConfig.proofServer, zkConfigProvider),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

async function connect(
  providers: Awaited<ReturnType<typeof createProviders>>,
  options: { privateStateId: string; initialPrivateState?: Record<string, unknown> },
): Promise<any> {
  return findDeployedContract(providers, {
    compiledContract: compiledContract as any,
    contractAddress: deployment.address,
    privateStateId: options.privateStateId,
    ...(options.initialPrivateState ? { initialPrivateState: options.initialPrivateState } : {}),
  });
}

function circuitOutputToBytes(result: any): Buffer {
  const value: Array<Uint8Array> = result?.private?.output?.value ?? [];
  return Buffer.concat(value);
}

async function readLedger(providers: Awaited<ReturnType<typeof createProviders>>) {
  const contractState = await providers.publicDataProvider.queryContractState(deployment.address);
  return contractState ? decodeLedger(contractState.data) : null;
}

// Serialize all chain mutations — the wallet is single-threaded.
let chainQueue: Promise<unknown> = Promise.resolve();
function enqueue<T>(fn: () => Promise<T>): Promise<T> {
  const run = chainQueue.then(fn, fn);
  chainQueue = run.catch(() => undefined);
  return run;
}

// ─── App state ─────────────────────────────────────────────────────────────────

let providers: Awaited<ReturnType<typeof createProviders>>;
let walletCtx: WalletContext;
let admin: any;

async function updateStatus() {
  const ledger = await readLedger(providers);
  if (!ledger) return null;
  const ballots = Number((ledger.ballots as unknown as { size(): number }).size());
  const forV = Number(ledger.tallyFor);
  const againstV = Number(ledger.tallyAgainst);
  return {
    ok: true,
    network,
    contractAddress: deployment.address,
    question: ledger.question,
    state: Number(ledger.state),
    stateLabel: Number(ledger.state) === 0 ? 'OPEN' : Number(ledger.state) === 1 ? 'CLOSED' : String(ledger.state),
    for: forV,
    against: againstV,
    ballots,
    authority: `0x${toHex(ledger.authority)}`,
    auditOk: ballots === forV + againstV,
    // Network service URLs — used as fallbacks by the browser-driven vote
    // path when the connected Lace wallet config lacks them.
    indexer: networkConfig.indexer,
    indexerWS: networkConfig.indexerWS,
    node: networkConfig.node,
    proofServer: networkConfig.proofServer,
    syncedAt: Date.now(),
  };
}

// ─── HTTP helpers ──────────────────────────────────────────────────────────────

function cors(res: ServerResponse): void {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Max-Age', '86400');
}

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  cors(res);
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(payload),
    'Cache-Control': 'no-store',
  });
  res.end(payload);
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (chunk) => (data += chunk));
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

// ─── Routing ───────────────────────────────────────────────────────────────────

async function handleApi(req: IncomingMessage, res: ServerResponse, url: URL): Promise<void> {
  if (url.pathname === '/api/status') {
    try {
      const status = await updateStatus();
      if (!status) return sendJson(res, 503, { ok: false, error: 'No contract state on-chain yet' });
      return sendJson(res, 200, status);
    } catch (err) {
      return sendJson(res, 500, { ok: false, error: (err as Error).message });
    }
  }

  if (url.pathname === '/api/balance') {
    try {
      await walletCtx.wallet.waitForSyncedState();
      const state = await walletCtx.wallet.waitForSyncedState();
      const night = state.unshielded.balances[unshieldedToken().raw] ?? 0n;
      const dust = state.dust.balance(new Date());
      return sendJson(res, 200, {
        ok: true,
        address: walletCtx.unshieldedKeystore.getBech32Address().toString(),
        tNight: night.toString(),
        dust: dust.toString(),
      });
    } catch (err) {
      return sendJson(res, 500, { ok: false, error: (err as Error).message });
    }
  }

  if ((url.pathname === '/api/vote' || url.pathname === '/api/close') && req.method === 'POST') {
    try {
      const result = await enqueue(async () => {
        const ledger = await readLedger(providers);
        if (!ledger) throw new Error('No contract state on-chain');

        if (url.pathname === '/api/vote') {
          if (Number(ledger.state) !== 0) throw new Error('Election is already closed');
          const body = await readBody(req);
          const { choice } = JSON.parse(body || '{}') as { choice?: string };
          if (choice !== 'for' && choice !== 'against') {
            throw new Error("choice must be 'for' or 'against'");
          }
          const forVote = choice === 'for';

          const secret = newBallotSecret();
          const expectedId = ballotIdFromSecret(secret);
          const voter = await connect(providers, {
            privateStateId: `web-voter-${toHex(secret).slice(0, 16)}`,
            initialPrivateState: { ballotSecret: secret },
          });

          const tx = await voter.callTx.castVote(forVote);
          const ballotId = circuitOutputToBytes(tx);
          const matched = Buffer.from(ballotId).equals(Buffer.from(expectedId));
          return {
            ok: true,
            choice,
            ballotId: `0x${toHex(ballotId)}`,
            matchesPrediction: matched,
            txId: tx.public.txId,
            blockHeight: Number(tx.public.blockHeight),
          };
        }

        if (Number(ledger.state) !== 0) return { ok: true, alreadyClosed: true, error: 'Election already closed' };
        const tx = await admin.callTx.closeElection();
        return {
          ok: true,
          txId: tx.public.txId,
          blockHeight: Number(tx.public.blockHeight),
        };
      });
      return sendJson(res, 200, result);
    } catch (err) {
      const msg = (err as Error).message || String(err);
      const status = msg.includes('already cast a ballot') || msg.includes('already closed') ? 409 : 200;
      return sendJson(res, status, { ok: false, error: msg });
    }
  }

  return sendJson(res, 404, { ok: false, error: 'Not found' });
}

// ─── ZK artifacts over HTTP (for the browser FetchZkConfigProvider) ──────────

const ZK_EXTENSION_BY_KIND: Record<string, readonly string[]> = {
  keys: ['prover', 'verifier'] as const,
  zkir: ['bzkir'] as const,
};

/**
 * Serve `/zkconfig/<tag>/<keys|zkir>/<name>.<ext>` from the compiled contract
 * output. `FetchZkConfigProvider` requests
 *   keys/<circuitId>.prover, keys/<circuitId>.verifier, zkir/<circuitId>.bzkir
 * The regexp whitelist keeps path traversal out of the file resolution.
 */
function serveZkConfig(res: ServerResponse, url: URL): void {
  const match = url.pathname.match(/^\/zkconfig\/([A-Za-z0-9-]+)\/(keys|zkir)\/([A-Za-z0-9_-]+)\.(prover|verifier|bzkir)$/);
  if (!match) return sendJson(res, 404, { ok: false, error: 'Not found' });
  const [, tag, kind, name, ext] = match;
  if (tag !== CONTRACT_TAG) return sendJson(res, 404, { ok: false, error: 'Unknown contract tag' });
  const allowed = ZK_EXTENSION_BY_KIND[kind];
  if (!allowed || !allowed.includes(ext)) return sendJson(res, 404, { ok: false, error: 'Not found' });

  const file = path.join(zkConfigPath, kind, `${name}.${ext}`);
  if (!fs.existsSync(file)) return sendJson(res, 404, { ok: false, error: 'ZK artifact not found' });

  const data = fs.readFileSync(file);
  cors(res);
  res.writeHead(200, {
    'Content-Type': 'application/octet-stream',
    'Content-Length': data.length,
    'Cache-Control': 'public, max-age=600',
  });
  res.end(data);
}

// ─── HTTP server ───────────────────────────────────────────────────────────────

function createApp() {
  return createServer(async (req, res) => {
    const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`);

    if (req.method === 'OPTIONS') {
      cors(res);
      res.writeHead(204);
      res.end();
      return;
    }

    if (url.pathname === '/' || url.pathname === '/health') {
      sendJson(res, 200, { ok: true, service: 'pearpass-api', port: PORT, network });
      return;
    }

    if (url.pathname.startsWith('/zkconfig/')) {
      serveZkConfig(res, url);
      return;
    }

    if (url.pathname.startsWith('/api/')) {
      await handleApi(req, res, url);
      return;
    }

    sendJson(res, 404, { ok: false, error: 'Not found' });
  });
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n  Starting PearPass web app...\n');

  const syncStart = Date.now();
  console.log('  Building wallet and syncing with network (first run can take minutes)...');
  walletCtx = await createWallet({ network, networkConfig, seed: SEED });
  await walletCtx.wallet.waitForSyncedState();
  console.log(`  ✓ Synced in ${Math.round((Date.now() - syncStart) / 1000)}s`);
  await persistWalletState(network, walletCtx);

  providers = await createProviders(walletCtx);
  admin = await connect(providers, { privateStateId: ADMIN_PRIVATE_STATE_ID });

  const ledger = await readLedger(providers);
  console.log(`  Contract:  ${deployment.address}`);
  console.log(`  Network:   ${network}`);
  console.log(`  Question:  "${ledger?.question ?? '(unknown)'}"`);

  const server = createApp();
  server.listen(PORT, () => {
    console.log('');
    console.log(`  ✅ PearPass API running on port ${PORT} (CORS enabled):`);
    console.log(`     • GET  http://localhost:${PORT}/api/status`);
    console.log(`     • POST http://localhost:${PORT}/api/vote`);
    console.log(`     • POST http://localhost:${PORT}/api/close`);
    console.log('');
  });

  const shutdown = async () => {
    console.log('\n\n  Shutting down...');
    try {
      await persistWalletState(network, walletCtx);
      await walletCtx.wallet.stop();
    } catch {
      // best effort
    }
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 3000).unref();
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch(async (err) => {
  console.error('\n❌ Server failed to start:', (err as Error).stack ?? err);
  process.exit(1);
});